# Generated by Django 5.1.5 on 2026-03-01 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.CharField(help_text='SHA256 hash of API key', max_length=255, unique=True)),
                ('key_prefix', models.CharField(help_text="Display prefix like 'sk_live_XyZ'", max_length=12)),
                ('name', models.CharField(help_text="e.g., 'Production Key', 'Test Key'", max_length=255)),
                ('scopes', models.JSONField(blank=True, default=list, help_text="['leads:write', 'calls:read']")),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export')], max_length=20)),
                ('resource_type', models.CharField(choices=[('lead', 'Lead'), ('agent', 'Agent'), ('call', 'Call'), ('campaign', 'Campaign'), ('api_key', 'API Key'), ('settings', 'Company Settings')], max_length=50)),
                ('resource_id', models.UUIDField()),
                ('changes', models.JSONField(blank=True, help_text='{"field": ["old", "new"]}', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='call_credits_remaining',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='company',
            name='default_voice_provider',
            field=models.CharField(default='elevenlabs', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='max_agents',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='company',
            name='max_concurrent_calls',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='company',
            name='plan_tier',
            field=models.CharField(default='free', help_text='free, starter, pro, enterprise', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'created_at'], name='accounts_co_is_acti_95a29f_idx'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='api_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='accounts.apikey'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['key_hash'], name='accounts_ap_key_has_530f60_idx'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['company', 'is_active'], name='accounts_ap_company_10ffdf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'timestamp'], name='accounts_au_company_c53675_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['resource_type', 'resource_id'], name='accounts_au_resourc_30880d_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['employee', 'timestamp'], name='accounts_au_employe_068292_idx'),
        ),
    ]
