# Generated by Django 5.1.5 on 2026-03-01 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apikey_auditlog_company_call_credits_remaining_and_more'),
        ('campaigns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('leads_created', models.IntegerField(default=0)),
                ('leads_contacted', models.IntegerField(default=0)),
                ('leads_completed', models.IntegerField(default=0)),
                ('calls_total', models.IntegerField(default=0)),
                ('calls_answered', models.IntegerField(default=0)),
                ('calls_no_answer', models.IntegerField(default=0)),
                ('calls_failed', models.IntegerField(default=0)),
                ('calls_voicemail', models.IntegerField(default=0)),
                ('total_call_duration_seconds', models.IntegerField(default=0)),
                ('avg_call_duration_seconds', models.FloatField(default=0)),
                ('max_call_duration_seconds', models.IntegerField(default=0)),
                ('total_tokens_consumed', models.IntegerField(default=0)),
                ('total_voice_minutes', models.FloatField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('answer_rate', models.FloatField(default=0, help_text='calls_answered / calls_total')),
                ('success_rate', models.FloatField(default=0, help_text='disposition=completed / calls_total')),
                ('avg_sentiment_score', models.FloatField(blank=True, null=True)),
                ('positive_sentiment_count', models.IntegerField(default=0)),
                ('negative_sentiment_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'campaign daily stats',
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='allowed_calling_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='default_voice_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='spent_to_date_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='total_budget_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='voice_provider',
            field=models.CharField(default='elevenlabs', max_length=50),
        ),
        migrations.AddField(
            model_name='campaign',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='agent_id',
            field=models.CharField(blank=True, help_text='External agent reference', max_length=255),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='call_flow_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='phone_no',
            field=models.CharField(help_text='Caller ID number', max_length=20),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['company', 'status', 'created_at'], name='campaigns_c_company_908ffe_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active', 'deleted_at'], name='campaigns_c_is_acti_c8a00a_idx'),
        ),
        migrations.AddField(
            model_name='campaigndailystats',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='campaigndailystats',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_daily_stats', to='accounts.company'),
        ),
        migrations.AddIndex(
            model_name='campaigndailystats',
            index=models.Index(fields=['company', 'date'], name='campaigns_c_company_375fff_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigndailystats',
            index=models.Index(fields=['campaign', 'date'], name='campaigns_c_campaig_846c3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaigndailystats',
            unique_together={('campaign', 'date')},
        ),
    ]
