# Generated by Django 5.1.5 on 2026-03-01 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_apikey_auditlog_company_call_credits_remaining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('integration_type', models.CharField(choices=[('salesforce', 'Salesforce'), ('hubspot', 'HubSpot'), ('pipedrive', 'Pipedrive'), ('zoho', 'Zoho CRM'), ('slack', 'Slack'), ('zapier', 'Zapier'), ('custom_webhook', 'Custom Webhook')], max_length=50)),
                ('name', models.CharField(help_text='Display name for this integration', max_length=255)),
                ('credentials', models.JSONField(help_text='Encrypted API keys, tokens, etc.')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Integration-specific settings')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('sync_leads', 'Sync Leads'), ('push_call_data', 'Push Call Data'), ('pull_contacts', 'Pull Contacts'), ('update_deal', 'Update Deal')], max_length=50)),
                ('success', models.BooleanField(default=False)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_succeeded', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integration',
            index=models.Index(fields=['company', 'is_active'], name='integration_company_3138bc_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', 'created_at'], name='integration_integra_8c5170_idx'),
        ),
    ]
