# Generated by Django 5.1.5 on 2026-03-01 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_apikey_auditlog_company_call_credits_remaining_and_more'),
        ('agents', '0001_initial'),
        ('campaigns', '0002_campaigndailystats_campaign_allowed_calling_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('file_url', models.URLField(help_text='S3 location', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_imports', models.IntegerField(default=0)),
                ('failed_imports', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='[{"row": 5, "error": "Invalid phone"}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_import_batches', to='agents.agent')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_import_batches', to='campaigns.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_import_batches', to='accounts.company')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_e164', models.CharField(help_text='E.164 format: +14155552671', max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('country', models.CharField(blank=True, help_text='ISO 2-letter code', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, default='America/New_York', max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('done', 'Done'), ('stopped', 'Stopped')], default='new', max_length=20)),
                ('disposition', models.CharField(blank=True, choices=[('not_interested', 'Not Interested'), ('hung_up', 'Hung Up'), ('completed', 'Completed'), ('no_answer', 'No Answer'), ('callback_requested', 'Callback Requested'), ('voicemail', 'Voicemail Left'), ('wrong_number', 'Wrong Number'), ('dnc', 'Do Not Call')], max_length=50, null=True)),
                ('attempts_count', models.IntegerField(default=0)),
                ('successful_contact_count', models.IntegerField(default=0, help_text='Times actually spoke')),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, help_text='company_verified, twilio_lookup', max_length=50)),
                ('phone_carrier', models.CharField(blank=True, max_length=100)),
                ('phone_type', models.CharField(blank=True, help_text='mobile, landline, voip', max_length=20)),
                ('schedule_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_called_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('do_not_call_before', models.TimeField(blank=True, help_text='e.g., 09:00', null=True)),
                ('do_not_call_after', models.TimeField(blank=True, help_text='e.g., 20:00', null=True)),
                ('currently_in_call', models.BooleanField(default=False)),
                ('call_lock_acquired_at', models.DateTimeField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, help_text='{"company": "Acme Corp", "title": "VP Sales", "linkedin": "https://..."}')),
                ('tags', models.JSONField(blank=True, default=list, help_text='["high-value", "warm-lead"]')),
                ('lead_score', models.IntegerField(blank=True, help_text='0-100 score', null=True)),
                ('source', models.CharField(blank=True, help_text='csv_upload, api, crm_sync', max_length=100)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='agents.agent')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='campaigns.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_deleted', to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadimportbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_notes_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='leads.lead')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status', 'created_at'], name='leads_lead_company_bae5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['agent', 'status'], name='leads_lead_agent_i_69cbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['campaign', 'status'], name='leads_lead_campaig_77d466_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone_e164', 'company'], name='leads_lead_phone_e_61ee2e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['schedule_at'], name='leads_lead_schedul_6d3e38_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['currently_in_call'], name='leads_lead_current_654239_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'schedule_at'], name='leads_lead_scheduler_idx'),
        ),
    ]
