# Generated by Django 5.1.5 on 2026-03-01 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_apikey_auditlog_company_call_credits_remaining_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('leads_csv', 'Leads CSV'), ('calls_csv', 'Calls CSV'), ('transcripts_zip', 'Transcripts ZIP'), ('analytics_excel', 'Analytics Excel'), ('full_backup', 'Full Data Backup')], max_length=50)),
                ('filters', models.JSONField(help_text='{"campaign_id": "...", "date_range": [...]}')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True, help_text='S3 signed URL', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(help_text='Download link expires after 24hrs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_exports', to='accounts.company')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_exports_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
