# Generated by Django 5.1.5 on 2026-03-01 07:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_apikey_auditlog_company_call_credits_remaining_and_more'),
        ('campaigns', '0002_campaigndailystats_campaign_allowed_calling_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g., 'Professional Male', 'Friendly Female'", max_length=255)),
                ('provider', models.CharField(help_text='elevenlabs, google, azure', max_length=50)),
                ('voice_id', models.CharField(help_text="Provider's voice ID", max_length=255)),
                ('language_code', models.CharField(default='en-US', max_length=10)),
                ('speed', models.FloatField(default=1.0, help_text='0.5 to 2.0')),
                ('pitch', models.FloatField(default=1.0, help_text='0.5 to 2.0')),
                ('stability', models.FloatField(default=0.5, help_text='ElevenLabs specific')),
                ('similarity_boost', models.FloatField(default=0.75, help_text='ElevenLabs specific')),
                ('sample_audio_url', models.URLField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_configs', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('testing', 'Testing')], default='active', max_length=20)),
                ('prompt', models.TextField(help_text='System prompt / instructions for the AI')),
                ('welcome_message', models.TextField(help_text='First thing agent says')),
                ('fallback_message', models.TextField(blank=True, help_text="When agent doesn't understand")),
                ('goodbye_message', models.TextField(blank=True)),
                ('voice_id', models.UUIDField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(default=3, help_text='Max call attempts per lead')),
                ('retry_delay_minutes', models.IntegerField(default=60)),
                ('max_call_duration_minutes', models.IntegerField(default=15)),
                ('interrupt_threshold', models.FloatField(default=0.5, help_text='How easily user can interrupt (0-1)')),
                ('model_name', models.CharField(default='gpt-4-turbo', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=150)),
                ('knowledge_base_text', models.TextField(blank=True, help_text='Additional context for agent')),
                ('knowledge_base_urls', models.JSONField(blank=True, default=list, help_text='["https://..."]')),
                ('enable_human_handoff', models.BooleanField(default=False)),
                ('handoff_phone_number', models.CharField(blank=True, max_length=20)),
                ('handoff_triggers', models.JSONField(blank=True, default=list, help_text='["angry", "request manager"]')),
                ('total_calls', models.IntegerField(default=0)),
                ('successful_calls', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='campaigns.campaign')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='accounts.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_updated', to=settings.AUTH_USER_MODEL)),
                ('voice_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='agents.voiceconfiguration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('configuration_snapshot', models.JSONField(help_text='Full agent config at this version')),
                ('calls_with_this_version', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(blank=True, null=True)),
                ('success_rate', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Currently deployed version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='agents.agent')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('agent', 'version_number')},
            },
        ),
        migrations.AddIndex(
            model_name='voiceconfiguration',
            index=models.Index(fields=['company', 'is_active'], name='agents_voic_company_077cae_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['company', 'status'], name='agents_agen_company_4a0a6b_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['campaign', 'status'], name='agents_agen_campaig_28615d_idx'),
        ),
    ]
