# Generated by Django 5.1.5 on 2026-03-01 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_apikey_auditlog_company_call_credits_remaining_and_more'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=20)),
                ('sentiment_score', models.FloatField(blank=True, help_text='-1.0 to 1.0', null=True)),
                ('key_points', models.JSONField(blank=True, default=list, help_text='["interested in product", "budget concerns"]')),
                ('topics_discussed', models.JSONField(blank=True, default=list)),
                ('objections_raised', models.JSONField(blank=True, default=list)),
                ('intent_detected', models.CharField(blank=True, help_text='purchase_intent, information_gathering', max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('next_actions', models.JSONField(blank=True, default=list, help_text='["send pricing", "schedule demo"]')),
                ('recommendations', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voice_provider', models.CharField(max_length=50)),
                ('voice_minutes', models.FloatField(default=0)),
                ('voice_cost_per_minute', models.DecimalField(decimal_places=4, max_digits=10)),
                ('voice_total_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ai_provider', models.CharField(default='openai', max_length=50)),
                ('ai_tokens_consumed', models.IntegerField(default=0)),
                ('ai_cost_per_token', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ai_total_cost', models.DecimalField(decimal_places=4, max_digits=10)),
                ('phone_provider', models.CharField(blank=True, max_length=50)),
                ('phone_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CallRecording',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_bucket', models.CharField(blank=True, max_length=255)),
                ('s3_key', models.CharField(blank=True, max_length=500)),
                ('s3_url', models.URLField(help_text='Permanent S3 URL', max_length=500)),
                ('signed_url', models.URLField(blank=True, help_text='Temporary signed URL', max_length=1000)),
                ('signed_url_expires_at', models.DateTimeField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('format', models.CharField(default='mp3', help_text='mp3, wav, etc.', max_length=20)),
                ('retain_until', models.DateTimeField(blank=True, help_text='Auto-delete after this date', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='scheduled', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('answered', 'Answered'), ('no_answer', 'No Answer'), ('busy', 'Busy'), ('failed', 'Failed'), ('voicemail', 'Voicemail')], max_length=20, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('tokens_consumed', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('transcript_url', models.URLField(blank=True, max_length=500)),
                ('recording_url', models.URLField(blank=True, max_length=500)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='agents.agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
