# Generated by Django 5.1.5 on 2026-03-01 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calls', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='calls.call'),
        ),
        migrations.AddField(
            model_name='callcost',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='calls.call'),
        ),
        migrations.AddField(
            model_name='callrecording',
            name='call',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='calls.call'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['lead', 'status'], name='calls_call_lead_id_5803c4_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['agent', 'status'], name='calls_call_agent_i_644724_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['company', 'created_at'], name='calls_call_company_82c110_idx'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['status', 'scheduled_at'], name='calls_call_status_c45e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='callrecording',
            index=models.Index(fields=['retain_until', 'is_deleted'], name='calls_callr_retain__802aca_idx'),
        ),
    ]
